import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

class Database implements AutoCloseable {
    private static final String URL = "jdbc:h2:./data/gasflaschen;DB_CLOSE_DELAY=-1";
    private final Connection connection;

    Database() {
        try {
            Class.forName("org.h2.Driver");
            connection = DriverManager.getConnection(URL);
            createTables();
        } catch (ClassNotFoundException exception) {
            throw new IllegalStateException("H2-Treiber fehlt im Laufzeit-Classpath.", exception);
        } catch (SQLException exception) {
            throw new IllegalStateException("Datenbank konnte nicht geöffnet werden.", exception);
        }
    }

    void addRoom(String name) {
        executeUpdate("MERGE INTO rooms (name) KEY (name) VALUES (?)", name);
    }

    void addGasflasche(String nummer) {
        executeUpdate("MERGE INTO gasflaschen (nummer) KEY (nummer) VALUES (?)", nummer);
    }

    void moveGasflasche(String nummer, String roomName) {
        try {
            connection.setAutoCommit(false);
            long roomId = findRoomId(roomName);
            if (!exists("SELECT 1 FROM gasflaschen WHERE nummer = ?", nummer)) {
                throw new IllegalArgumentException("Unbekannte Flaschennummer: " + nummer);
            }

            try (PreparedStatement statement = connection.prepareStatement(
                    "UPDATE gasflaschen SET room_id = ? WHERE nummer = ?")) {
                statement.setLong(1, roomId);
                statement.setString(2, nummer);
                statement.executeUpdate();
            }
            connection.commit();
        } catch (SQLException | RuntimeException exception) {
            rollback();
            throw exception instanceof RuntimeException runtimeException
                    ? runtimeException
                    : new IllegalStateException("Flasche konnte nicht verschoben werden.", exception);
        } finally {
            setAutoCommit();
        }
    }

    List<Room> getRooms() {
        List<Room> rooms = new ArrayList<>();
        try (PreparedStatement statement = connection.prepareStatement(
                "SELECT id, name FROM rooms ORDER BY name");
             ResultSet result = statement.executeQuery()) {
            while (result.next()) {
                Room room = new Room(result.getString("name"));
                loadGasflaschen(room, result.getLong("id"));
                rooms.add(room);
            }
            return rooms;
        } catch (SQLException exception) {
            throw new IllegalStateException("Räume konnten nicht geladen werden.", exception);
        }
    }

    private void createTables() throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate(
                "CREATE TABLE IF NOT EXISTS rooms ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(255) NOT NULL UNIQUE)"
            );
            statement.executeUpdate(
                "CREATE TABLE IF NOT EXISTS gasflaschen ("
                    + "nummer VARCHAR(255) PRIMARY KEY, "
                    + "room_id BIGINT, "
                    + "FOREIGN KEY (room_id) REFERENCES rooms(id))"
            );
        }
    }

    private long findRoomId(String roomName) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "SELECT id FROM rooms WHERE name = ?")) {
            statement.setString(1, roomName);
            try (ResultSet result = statement.executeQuery()) {
                if (!result.next()) {
                    throw new IllegalArgumentException("Unbekannter Raum: " + roomName);
                }
                return result.getLong("id");
            }
        }
    }

    private void loadGasflaschen(Room room, long roomId) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(
                "SELECT nummer FROM gasflaschen WHERE room_id = ? ORDER BY nummer")) {
            statement.setLong(1, roomId);
            try (ResultSet result = statement.executeQuery()) {
                while (result.next()) {
                    room.addGasflasche(new Gasflasche(result.getString("nummer")));
                }
            }
        }
    }

    private boolean exists(String sql, String value) throws SQLException {
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, value);
            try (ResultSet result = statement.executeQuery()) {
                return result.next();
            }
        }
    }

    private void executeUpdate(String sql, String value) {
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, value);
            statement.executeUpdate();
        } catch (SQLException exception) {
            throw new IllegalArgumentException("Datenbankänderung konnte nicht gespeichert werden.", exception);
        }
    }

    private void rollback() {
        try {
            connection.rollback();
        } catch (SQLException ignored) {
            // Die ursprüngliche Exception ist für den Aufrufer aussagekräftiger.
        }
    }

    private void setAutoCommit() {
        try {
            connection.setAutoCommit(true);
        } catch (SQLException exception) {
            throw new IllegalStateException("Datenbankverbindung konnte nicht zurückgesetzt werden.", exception);
        }
    }

    @Override
    public void close() {
        try {
            connection.close();
        } catch (SQLException exception) {
            throw new IllegalStateException("Datenbankverbindung konnte nicht geschlossen werden.", exception);
        }
    }
}