package de.bottletracking;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class DataInitializer implements CommandLineRunner {
    private final JdbcTemplate jdbc;

    public DataInitializer(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
    }

    @Override
    public void run(String... args) {
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS stations (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(80) NOT NULL UNIQUE,
                color VARCHAR(30) NOT NULL
            )
            """);
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS rooms (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(120) NOT NULL UNIQUE,
                station_id BIGINT,
                CONSTRAINT fk_room_station FOREIGN KEY (station_id) REFERENCES stations(id)
            )
            """);
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS bottles (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                code VARCHAR(120) NOT NULL UNIQUE,
                status VARCHAR(30) NOT NULL,
                note VARCHAR(1000),
                current_room_id BIGINT,
                CONSTRAINT fk_bottle_room FOREIGN KEY (current_room_id) REFERENCES rooms(id)
            )
            """);
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS bottle_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                bottle_id BIGINT NOT NULL,
                from_room_id BIGINT,
                to_room_id BIGINT,
                action VARCHAR(40) NOT NULL,
                changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
                changed_by VARCHAR(80) NOT NULL,
                CONSTRAINT fk_history_bottle FOREIGN KEY (bottle_id) REFERENCES bottles(id)
            )
            """);

        if (jdbc.queryForObject("SELECT COUNT(*) FROM stations", Integer.class) == 0) {
            jdbc.update("INSERT INTO stations (name, color) VALUES (?, ?), (?, ?), (?, ?), (?, ?)",
                "Nord", "mint", "Süd", "coral", "West", "blue", "Ost", "yellow");
        }
        if (jdbc.queryForObject("SELECT COUNT(*) FROM rooms", Integer.class) == 0) {
            jdbc.update("INSERT INTO rooms (name, station_id) SELECT ?, id FROM stations WHERE name = ?", "Room 101", "Nord");
            jdbc.update("INSERT INTO rooms (name, station_id) SELECT ?, id FROM stations WHERE name = ?", "Room 102", "Süd");
        }
    }
}
